default: &default
  mail_from: 'onboarding@resend.dev'

development:
  <<: *default
  app_host: 'localhost:3002'

test:
  <<: *default
  app_host: 'localhost:3002'

production:
  <<: *default
  app_host: <%= ENV['APP_HOST'] %>
